package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func runConfigureCmd() {
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintln(os.Stderr, "wAURden: cannot determine home directory")
		os.Exit(1)
	}

	configPath := filepath.Join(home, ".config", "waurden", "config.toml")

	fmt.Println("wAURden — your guardian for the AUR")
	fmt.Println("Configuration wizard")
	fmt.Println()

	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("Config file already exists: %s\n", configPath)
		if !promptYN("Overwrite it?", false) {
			fmt.Println("Aborted.")
			return
		}
		fmt.Println()
	}

	fmt.Println("wAURden needs an LLM provider to analyze PKGBUILDs.")
	fmt.Println("Choose a provider:")
	fmt.Println("  1) Anthropic Claude (recommended — claude-haiku-4-5 is fast and cheap)")
	fmt.Println("  2) OpenAI (GPT-4o-mini or similar)")
	fmt.Println("  3) OpenAI-compatible endpoint (Ollama, Gemini, OpenRouter, etc.)")
	fmt.Println("  4) Static — heuristics only, no LLM (limited protection, no API key needed)")
	fmt.Println()

	choice := promptChoice("Provider", []string{"1", "2", "3", "4"}, "1")

	var provider, model, baseURL, apiKeyEnv string

	switch choice {
	case "1":
		provider = "anthropic"
		model = promptString("Model", "claude-haiku-4-5")
		apiKeyEnv = promptString("Environment variable holding your API key", "ANTHROPIC_API_KEY")
	case "2":
		provider = "openai"
		model = promptString("Model", "gpt-4o-mini")
		apiKeyEnv = promptString("Environment variable holding your API key", "OPENAI_API_KEY")
	case "3":
		provider = "openai"
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  Ollama (local):  http://localhost:11434/v1")
		fmt.Println("  Gemini:          https://generativelanguage.googleapis.com/v1beta/openai")
		fmt.Println("  OpenRouter:      https://openrouter.ai/api/v1")
		baseURL = promptString("Base URL", "http://localhost:11434/v1")
		model = promptString("Model name", "llama3")
		apiKeyEnv = promptString("Environment variable holding your API key (leave blank if none)", "")
	case "4":
		provider = "static"
		fmt.Println()
		fmt.Println("Static mode: heuristic pattern matching only, no LLM calls.")
		fmt.Println("This catches known-bad patterns (curl|bash, ssh exfiltration, etc.) but")
		fmt.Println("cannot reason about novel or obfuscated attacks. Consider using an LLM provider")
		fmt.Println("for stronger protection.")
	}

	fmt.Println()
	fmt.Println("Policy settings (press Enter to accept defaults):")

	onError := promptChoice(
		"When LLM scan fails: warn (allow build with warning), block (abort build), allow (silent)",
		[]string{"warn", "block", "allow"},
		"warn",
	)

	fmt.Println()
	fmt.Println("Summary:")
	fmt.Printf("  Provider:    %s\n", provider)
	if model != "" {
		fmt.Printf("  Model:       %s\n", model)
	}
	if baseURL != "" {
		fmt.Printf("  Base URL:    %s\n", baseURL)
	}
	if apiKeyEnv != "" {
		fmt.Printf("  API key env: %s\n", apiKeyEnv)
	}
	fmt.Printf("  On error:    %s\n", onError)
	fmt.Printf("  Config file: %s\n", configPath)
	fmt.Println()

	if !promptYN("Write this configuration?", true) {
		fmt.Println("Aborted.")
		return
	}

	if err := os.MkdirAll(filepath.Dir(configPath), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "wAURden: cannot create config directory: %v\n", err)
		os.Exit(1)
	}

	content := buildConfigTOML(provider, model, baseURL, apiKeyEnv, onError)
	if err := os.WriteFile(configPath, []byte(content), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "wAURden: cannot write config: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Configuration written to %s\n", configPath)
	fmt.Println()

	if apiKeyEnv != "" {
		fmt.Printf("Make sure %s is set in your environment before running waurden.\n", apiKeyEnv)
	}
	if provider == "static" {
		fmt.Println("NOTE: static mode uses heuristics only. Re-run 'waurden configure' to set up an LLM provider.")
	}
}

func buildConfigTOML(provider, model, baseURL, apiKeyEnv, onError string) string {
	var sb strings.Builder
	sb.WriteString("# wAURden configuration\n")
	sb.WriteString("# Generated by 'waurden configure'\n\n")
	sb.WriteString(fmt.Sprintf("provider = %q\n", provider))
	if model != "" {
		sb.WriteString(fmt.Sprintf("model = %q\n", model))
	}
	if baseURL != "" {
		sb.WriteString(fmt.Sprintf("base_url = %q\n", baseURL))
	}
	if apiKeyEnv != "" {
		sb.WriteString(fmt.Sprintf("api_key_env = %q\n", apiKeyEnv))
	}
	sb.WriteString("\ntimeout_seconds = 60\n")
	sb.WriteString("\nblock_on = [\"malicious\"]\n")
	sb.WriteString("warn_on = [\"suspicious\"]\n")
	sb.WriteString(fmt.Sprintf("on_error = %q\n", onError))
	return sb.String()
}

var stdinReader *bufio.Reader

func stdin() *bufio.Reader {
	if stdinReader == nil {
		stdinReader = bufio.NewReader(os.Stdin)
	}
	return stdinReader
}

func promptString(label, defaultVal string) string {
	if defaultVal != "" {
		fmt.Printf("%s [%s]: ", label, defaultVal)
	} else {
		fmt.Printf("%s: ", label)
	}
	line, _ := stdin().ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	return line
}

func promptChoice(label string, choices []string, defaultVal string) string {
	fmt.Printf("%s [%s]: ", label, defaultVal)
	for {
		line, _ := stdin().ReadString('\n')
		line = strings.TrimSpace(line)
		if line == "" {
			return defaultVal
		}
		for _, c := range choices {
			if strings.EqualFold(line, c) {
				return c
			}
		}
		fmt.Printf("Please enter one of %s [%s]: ", strings.Join(choices, "/"), defaultVal)
	}
}

func promptYN(label string, defaultYes bool) bool {
	hint := "y/N"
	if defaultYes {
		hint = "Y/n"
	}
	fmt.Printf("%s [%s]: ", label, hint)
	line, _ := stdin().ReadString('\n')
	line = strings.TrimSpace(strings.ToLower(line))
	if line == "" {
		return defaultYes
	}
	return line == "y" || line == "yes"
}
